# Обновления {-}

## 2025-05-15 {-}
* Добавил несколько разделов в [Введение]
  * [Почему именно R, а не Python?]
  * [Чему вы научитесь, прочитав эту книгу]

## 2025-04-30 {-}
* Добавлена глава [Интегрируем в бота искусственный интеллект].
* У книги новая обложка.
* Доработано введение и заключения с учётом добавления новой главы.
* В главе [Построение последовательного, логического диалога с ботом] переписано заключение.
* 1 и 2 глава прошли повторную редактуру.
* Записано и добавлено на главную страницу новое видео "О курсе".

## 2025-04-27 {-}
* В главе [Добавляем боту поддержку команд и фильтры сообщений, класс Updater] расширен раздел [Запускаем бота в фоновом режиме], добавил информаци про [Запуск бота как отдельной службы].

## 2024-08-28 {-}
* Добавлена новая глава [Разворачиваем бота в облачных сервисах].

## 2024-08-02 {-}
* У книги новая обложка.
* В главу [Создаём бота, и отправляем с его помощью сообщения в telegram] добавлен раздел [Настраиваем запуск расписания отправки сообщения с помощью GitHub Actions].
* Во вторую главу [Добавляем боту поддержку команд и фильтры сообщений, класс Updater] добавлен раздел [Обработка голосовых сообщений. Переводим голосовое сообщение в текст]. В которой приведён пример бота, который преобразует голосовые сообщения в текст.
* Во вторую главу [Добавляем боту поддержку команд и фильтры сообщений, класс Updater] добавлен раздел [Бот для сбора статистики из Telegram чатов].
* К книге добавлено предисловие и заключение.
* В каждой главе переписаны предисловие и заключение.

## 2023-02-08 {-}
* В главе "[Как добавить боту поддержку клавиатуры]" переписан раздел "[Пример бота, который выводит список самых свежих статей со ссылками по-указанному Хабу из habr.com]". Ранее в этом разделе приводился код, в котором для парсинга информации о статьях использовался уже не актуальный пакет `habR`, теперь данный бот работает с RRS каналом Хабра, с помощью пакета `tidyRSS`.

## 2023-01-20 {-}
* В первую главу [Создаём бота, и отправляем с его помощью сообщения в telegram], добавлено описание всех методов бота.
* Во вторую главу [Добавляем боту поддержку команд и фильтры сообщений, класс Updater], добавлено описание методов обновлений.
* Во вторую главу [Добавляем боту поддержку команд и фильтры сообщений, класс Updater], добавлена информация о том, как запросить у пользователя номер телефона или локацию.

## 2022-09-06 {-}
* Добавлена 8 глава "[Упаковываем бота в Docker контейнер]".

## 2022-08-17 {-}
* Добавлена 7 глава "[Добавляем боту асинхронность]".

## 2022-08-09 {-}
* Практически во все уроки добавлены видео;
* Учебник переведён в формат bs4;
* Добавлена странца обновлений курса;
* Все ихсходники проекта учебника залиты на [github](https://github.com/selesnow/build_telegram_bot_using_r).
